package com.test.backuprestoredemo.backuprestore.models

/**
 * @param id hash id generated by google drive like 1dyGBkKvlNSgQYCw29jvQbG2x9fa2G5lirAG2rLu_6usMKmFscA
 * @param name original name of the file.
 * Media File : 1604389065693.mp4
 * DB File : 6042f0cc-ae8d-4f4a-bb39-740e60b1f400-NjlBNzU2OENFNTI5NjU2MTgyNTA2MkI5RUE3NzRCRDYtY29tLnNpbC5jb21tdW5pY2F0b3I=.db_1
 * @param path relative path of the file. It does not contain storage path or userId or deviceId
 * Media File : Media/Communicator Images/Sent/1604389368276.png
 * DB File : temp_db/6042f0cc-ae8d-4f4a-bb39-740e60b1f400-NjlBNzU2OENFNTI5NjU2MTgyNTA2MkI5RUE3NzRCRDYtY29tLnNpbC5jb21tdW5pY2F0b3I=.db_1
 * @param parent relative path of the parent of the file. (currently stored inside google drive)
 * Media File : Media/Communicator Images/Sent/
 * DB File : temp_db/
 * @param md5sum MD5 Hash to identify files contents are modified or not. It helps to prevent uploading the same content twice
 * */
data class FileInfo(val id : String, val name : String,val path : String, val parent : String, var md5sum : String)